# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title generate gibbs using Rcpp
#' @description generate gibbs using Rcpp
#' @param N the number of samples
#' @param mu1 Mean value of the first parameter
#' @param mu2 Mean value of the second parameter
#' @param sigma1 Standard deviation of the first parameter
#' @param sigma2 Standard deviation of the second parameter
#' @param rho correlation coefficient of the two parameter
#' @return a random sample of size \code{n}
#' @export
gibbs_cpp <- function(N, mu1, mu2, sigma1, sigma2, rho) {
    .Call('_StatComp22077_gibbs_cpp', PACKAGE = 'StatComp22077', N, mu1, mu2, sigma1, sigma2, rho)
}

